# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "rspec", "2.12.0"
gem "mocha", "0.13.1"
gem "simplecov", "0.7.1"

gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>3.3", :group => [:development, :test]

# vim: syntax=ruby
